### ISSUE TITLE
Error in if (lambda1 - Ey < 1e-06) lambda1 = 2 * Ey

### ISSUE THREAD

**Issue by jenzopr** [nghiavtr/BPSC#1]
Dear Trung,

I would like to try BPSC on our single cell data. Attached, you can find the (limited) expression table as Rdata file [tpm.zip](https://github.com/nghiavtr/BPSC/files/268099/tpm.zip). I executed the following code in R, which leads to the error:

```
library(BPSC)

load("tpm.Rdata")
group=c(rep(1,54),rep(2,81))
controlIds=which(group==1)
design=model.matrix(~group) 
coef=2 
res=BPglm(data=tmp, controlIds=controlIds, design=design, coef=coef, estIntPar=FALSE) 
```

The error is:

```
Error in if (lambda1 - Ey < 1e-06) lambda1 = 2 * Ey : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In mean.default(x/lambda2) :
  argument is not numeric or logical: returning NA
```

Do you have an idea why this error occurs?
Best,
Jens

**Comment by nghiavtr** [comment]
Hi Jens,

Thank you for your interest in BPSC! 
The error happens due to your data is not in matrix format. Just correct it by: tmp=as.matrix(tmp) , then the script works well.

Best,
Nghia

**Comment by jenzopr** [comment]
Makes perfectly sense! Thank you very much! 
Best,
Jens
