### ISSUE TITLE
install_github() now uses different package specification

### ISSUE THREAD

**Issue by plijnzaad** [nghiavtr/BPSC#3]
If you use 
```
install_github("BPSC","nghiavtr")
```
as per the README.md file, things won't work with newer versions of `devtools`, saying

```
Error in parse_repo_spec(repo) : Invalid git repo specification: 'BPSC'
```
It should look like 

```
install_github("nghiavtr/BPSC") 
```

which works perfectly.

**Comment by nghiavtr** [comment]
Dear Philip,

Many thanks for your comments.
I have updated the README.md as your suggestions.

Best wishes,
Nghia
